name: Deploy EKS and Pac-Man App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Check AWS CLI and Install kubectl
        run: |
          aws --version  # Check pre-installed AWS CLI
          # Install kubectl with fixed version
          curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

  terraform_deploy_eks:
    runs-on: ubuntu-latest
    needs: setup
    # environment: production

    steps:
      - name: Initialize Terraform
        run: |
          cd eks
          terraform init

      - name: Validate Terraform Configuration
        run: |
          cd eks
          terraform validate

      - name: Plan Terraform Deployment
        run: |
          cd eks
          terraform plan

      - name: Deploy EKS Cluster with Terraform
        run: |
          cd eks
          terraform apply -auto-approve

      - name: Configure kubectl for EKS
        run: |
          cd eks
          aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)

  deploy_pacman_app:
    runs-on: ubuntu-latest
    needs: terraform_deploy_eks
  #  environment: production

    steps:
      - name: Initialize Terraform for Pac-Man
        run: |
          cd pac-man
          terraform init

      - name: Validate Pac-Man Terraform Configuration
        run: |
          cd pac-man
          terraform validate

      - name: Plan Pac-Man Deployment
        run: |
          cd pac-man
          terraform plan

      - name: Deploy Pac-Man App with Terraform
        run: |
          cd pac-man
          terraform apply -auto-approve

      - name: Verify Pac-Man App Deployment
        run: |
          kubectl -n pac-man get all
