name: Deploy EKS and Pac-Man App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Check AWS CLI and Install kubectl
        run: |
          aws --version  # Verify AWS CLI
          # Install kubectl
          curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

  terraform_deploy_eks:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS CLI
        run: aws sts get-caller-identity

      - name: Initialize Terraform
        run: |
          cd eks
          terraform init \
            -backend-config="bucket=248189903023terraform-state-bucket" \
            -backend-config="key=eks/terraform.tfstate" \
            -backend-config="region=us-east-1"
        shell: bash

      - name: Validate Terraform Configuration
        run: |
          cd eks
          terraform validate
        shell: bash

      - name: Plan Terraform Deployment
        run: |
          cd eks
          terraform plan
        shell: bash

      - name: Deploy EKS Cluster with Terraform
        run: |
          cd eks
          terraform apply -auto-approve
        shell: bash

      - name: Configure kubectl for EKS
        run: |
          cd eks
          aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)
        shell: bash

  deploy_pacman_app:
    runs-on: ubuntu-latest
    needs: terraform_deploy_eks

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS CLI
        run: aws sts get-caller-identity

      - name: Initialize Terraform for Pac-Man
        run: |
          cd pac-man
          terraform init \
            -backend-config="bucket=248189903023terraform-state-bucket" \
            -backend-config="key=pac-man/terraform.tfstate" \
            -backend-config="region=us-east-1"
        shell: bash

      - name: Validate Pac-Man Terraform Configuration
        run: |
          cd pac-man
          terraform validate
        shell: bash

      - name: Plan Pac-Man Deployment
        run: |
          cd pac-man
          terraform plan
        shell: bash

      - name: Deploy Pac-Man App with Terraform
        run: |
          cd pac-man
          terraform apply -auto-approve
        shell: bash

      - name: Verify Pac-Man App Deployment
        run: |
          kubectl -n pac-man get all
        shell: bash
