name: Terraform Deploy

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure all files and history are fetched

      - name: Verify Terraform Directory
        run: ls -R ./terraform  # Debugging: Verify necessary files in the terraform directory

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.7.5'  # Updated to match your Init and Plan workflows

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -chdir=terraform  # Initialize modules and backend in the terraform directory

      - name: Verify Terraform Plan Artifact
        run: |
          if [ ! -f terraform/tfplan ]; then
            echo "Terraform plan file not found!"
            exit 1
          fi  # Ensure the tfplan file exists before applying

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan -chdir=terraform  # Apply the plan automatically with no prompts
