name: Terraform CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  terraform_init:
    name: Initialize Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Using the latest version of actions/checkout

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Using the latest stable version of setup-terraform
        with:
          terraform_version: '1.4.0'

      - name: Cache Terraform providers
        uses: actions/cache@v2  # Ensure actions/cache is referenced correctly
        with:
          path: ~/.terraform.d
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate  # Make sure this step is complete

      # Add other Terraform steps like plan or apply if needed
