name: Terraform Init

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  terraform-ci:
    name: 'Terraform CI Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files (optional, for debugging)
        run: ls -R  # To confirm that .tf files exist

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Ensure this is set to the directory with .tf files

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform  # Ensure this is set to the directory with .tf files
